version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/npm"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/pages"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
